/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: manoeldarochadeoliveira (https://sketchfab.com/manoeldarochadeoliveira)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/business-man-low-polygon-game-character-b6f6740f883b4749abac47af0045a9dd
Title: Business Man - Low Polygon game character
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function BusinessMan(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/businessMan/scene.gltf')
  const { actions,mixer } = useAnimations(animations, group)
  console.log(actions['Rig|idle'])
  return (
    <group ref={group} {...props} dispose={null} position={[10,-8,-50]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
          <group name="6faae247636341e9b36c6699f702b94ffbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Rig" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_78" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_80" position={[-0.011, 169.474, 7.083]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_82" position={[0.012, 170.333, 0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.business_suit_man} skeleton={nodes.Object_79.skeleton} />
                    <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.business_suit_man} skeleton={nodes.Object_81.skeleton} />
                    <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.business_suit_man} skeleton={nodes.Object_83.skeleton} />
                  </group>
                </group>
                <group name="Business_Male_Suit" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Business_Man_Internal_aParts" position={[-0.011, 169.474, 7.083]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Business_Man_Body" position={[0.012, 170.333, 0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/businessMan/scene.gltf')
