/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: durgaprasadpuppala (https://sketchfab.com/durgaprasadpuppala)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cushion-chair-40f47a44efd54271bfa6f0f71f896d58
Title: Cushion Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('/chair/scene.gltf')
  return (
    <group {...props} dispose={null} scale={10}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Cushion_Mat} position={[10,-4,-50]} />
    </group>
  )
}

useGLTF.preload('/chair/scene.gltf')
