/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: pjotr.van.schothorst (https://sketchfab.com/pjotr.van.schothorst)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/villa-lisse-simple-curtains-0e6a827c72d74a33a0942d108793bf89
Title: Villa Lisse - Simple Curtains
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props) {
  const { nodes, materials } = useGLTF('/house/house.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04} position={[0,-15,-100]}>
        <group position={[932.909, -34.219, 40.001]} rotation={[0, 0, -1.568]}>
          <mesh geometry={nodes.Living_Assemblies_05_453_Living_Assemblies_05_453Mat_0.geometry} material={materials.Living_Assemblies_05_453Mat} />
          <mesh geometry={nodes.Living_Assemblies_05_453_Living_Assemblies_05_453Mat_0_1.geometry} material={materials.Living_Assemblies_05_453Mat} />
        </group>
        <mesh geometry={nodes.Glass_1_Glass_1Mat_0.geometry} material={materials.Glass_1Mat} position={[-551.967, -473.717, 13]} />
        <mesh geometry={nodes.Bottom_floor_3_Bottom_floor_3Mat_0.geometry} material={materials.Bottom_floor_3Mat} position={[-586.967, -561.717, -20]} />
        <mesh geometry={nodes.Chimney_18_Chimney_18Mat_0.geometry} material={materials.Chimney_18Mat} position={[498.4, -561.717, -80.5]} />
        <mesh geometry={nodes.Dining_Assembly_21_29_Dining_Assembly_21_29Mat_0.geometry} material={materials.Dining_Assembly_21_29Mat} position={[-124.074, 95.763, 40]} />
        <mesh geometry={nodes.Walls_gr_floor_1_100_Walls_gr_floor_1_100Mat_0.geometry} material={materials.Walls_gr_floor_1_100Mat} position={[-450.967, -63.717, 40]} />
        <mesh geometry={nodes.Frame_105_Frame_105Mat_0.geometry} material={materials.Frame_105Mat} position={[-626.967, -601.717, 10]} />
        <mesh geometry={nodes.walls_backside_space_108_walls_backside_space_108Mat_0.geometry} material={materials.walls_backside_space_108Mat} position={[-491.467, -563.774, 0]} />
        <mesh geometry={nodes.Terrace_115_Terrace_115Mat_0.geometry} material={materials.Terrace_115Mat} position={[-622.967, -947.717, 10]} />
        <mesh geometry={nodes.Walls_Outside_and_1st_floor_116_Walls_Outside_and_1st_floor_116Mat_0.geometry} material={materials.Walls_Outside_and_1st_floor_116Mat} position={[-622.967, -597.717, 40]} />
        <mesh geometry={nodes.Floor_gr_fl_124_Floor_gr_fl_124Mat_0.geometry} material={materials.Floor_gr_fl_124Mat} position={[-486.467, -556.165, 40]} />
        <mesh geometry={nodes.Below_terrace_126_Below_terrace_126Mat_0.geometry} material={materials.Below_terrace_126Mat} position={[-622.967, -947.717, -10]} />
        <mesh geometry={nodes.Kitchen_Assembly_13_129_Kitchen_Assembly_13_129Mat_0.geometry} material={materials.Kitchen_Assembly_13_129Mat} position={[135.204, 613.074, 40]} />
        <mesh geometry={nodes.Office_Assemblies_18_269_Office_Assemblies_18_269Mat_0.geometry} material={materials.Office_Assemblies_18_269Mat} position={[896.638, 168.853, 40]} />
        <mesh geometry={nodes.Pictures_and_statue_655_Pictures_and_statue_655Mat_0.geometry} material={materials.Pictures_and_statue_655Mat} position={[265.573, 66.283, 40]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Piano_03_668_Piano_03_668Mat_0.geometry} material={materials.Piano_03_668Mat} position={[412.014, -379.635, 40]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.curtains_849_curtains_849Mat_0.geometry} material={materials.curtains_849Mat} position={[307.851, -480.64, 40.6]} />
        <mesh geometry={nodes.Flower_856_Flower_856Mat_0.geometry} material={materials.Flower_856Mat} position={[952.409, -310.975, 100.397]} rotation={[0, 0, -1.568]} />
      </group>
    </group>
  )
}

useGLTF.preload('/house/house.gltf')
